"""init tables

Revision ID: 0cc296b624e2
Revises: 
Create Date: 2023-07-29 20:00:30.274445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc296b624e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_buisness_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='dayofweekenum'), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('end_time_local', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_poll_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='storestatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_timezone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_timezone')
    op.drop_table('store_poll_status')
    op.drop_table('store_buisness_hours')
    # ### end Alembic commands ###
