"""adding index

Revision ID: 57263a1fb81c
Revises: a7a7ac19d61c
Create Date: 2023-07-31 23:07:20.750028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57263a1fb81c'
down_revision = 'a7a7ac19d61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_buisness_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_buisness_hours_store_id'), ['store_id'], unique=False)

    with op.batch_alter_table('store_poll_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_poll_status_store_id'), ['store_id'], unique=False)

    with op.batch_alter_table('store_timezone', schema=None) as batch_op:
        batch_op.drop_index('store_id')
        batch_op.create_index(batch_op.f('ix_store_timezone_store_id'), ['store_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_timezone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_timezone_store_id'))
        batch_op.create_index('store_id', ['store_id'], unique=False)

    with op.batch_alter_table('store_poll_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_poll_status_store_id'))

    with op.batch_alter_table('store_buisness_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_buisness_hours_store_id'))

    # ### end Alembic commands ###
