"""change store_id type to bigint

Revision ID: d3f295e2fe7a
Revises: 0cc296b624e2
Create Date: 2023-07-29 20:26:25.047949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3f295e2fe7a'
down_revision = '0cc296b624e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_buisness_hours', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('store_poll_status', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('store_timezone', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_timezone', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('store_poll_status', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('store_buisness_hours', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
